version: "3.0"
services:

  zookeeper:
    image: ubuntu/zookeeper
    ports:
      - 2181:2181
    environment:
      - TZ=UTC

  kafka:
    image: ubuntu/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - TZ=UTC
      - ZOOKEPER_HOST=host.docker.internal
      - ZOOKEPER_PORT=2181

  spark-master:
    image: bitnami/spark
    volumes:
      - .:/project
    ports:
      - 8080:8080
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  
  # cassandra:
  #   image: bitnami/cassandra
  #   ports:
  #     - 9042:9042

  python-scripts:
    image: python:3
    volumes:
      - .:/project
    depends_on:
      # - cassandra
      - kafka
      - spark-master
    command: ["python", "/project/scripts/starter.py"]
    

    