version: "3.0"
services:
  zookeeper:
    image: ubuntu/zookeeper
    ports:
      - 2181:2181
    environment:
      - TZ=UTC
  kafka:
    image: ubuntu/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - TZ=UTC
      - ZOOKEPER_HOST=host.docker.internal
      - ZOOKEPER_PORT=2181
  # zeppelin:
  #   image: apache/zeppelin:0.10.0
  #   depends_on:
  #     - kafka
  #   ports:
  #     - 8080:8080
  spark:
    image: bitnami/spark
    ports:
      - 8080:8080
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
  
  cassandra:
    image: bitnami/cassandra
    ports:
      - 9042:9042
