version: "3.0"
services:

  zookeeper:
    image: ubuntu/zookeeper
    ports:
      - 2181:2181
    environment:
      - TZ=UTC

  kafka:
    image: ubuntu/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      - TZ=UTC
      - ZOOKEPER_HOST=host.docker.internal
      - ZOOKEPER_PORT=2181

  spark-master:
    image: bitnami/spark
    volumes:
      - .:/project
    ports:
      - 8080:8080
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    command: "./bin/spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.3.0 /project/scripts/kafka_twitter_spark_streaming.py"

  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: "adminpwd"
      MYSQL_USER: "localuser"
      MYSQL_PASSWORD: "localpwd"
      MYSQL_DATABASE: "localdb"
    volumes:
      - .:/project

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  python-scripts:
    image: python:3
    volumes:
      - .:/project
    depends_on:
      - kafka
      - spark-master
    command: ["python", "/project/scripts/starter.py"]
    

    